sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) #Get latest commit SHA
    #- CLOUDSDK_CORE_DISABLE_PROMPTS=1 #Diables cloud CLI prompts
before_install:
  #- openssl aes-256-cbc -K $encrypted_12345_key -iv $encrypted_12345_iv -in service-account.json.enc -out service-account.json -d
  #- curl https://sdk.cloud.google.com | bash > /dev/null;
  #- source $HOME/google-cloud-sdk/path.bash.inc
  #- gcloud components update kubectl
  #- gcloud auth activate-service-account --key-file service-account.json
  #- gcloud config set project project-name
  #- gcloud config set compute/zone us-central1-account
  #- gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t adamgouldmig/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true adamgouldmig/react-test npm run test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
